[package]
name = "nativelink-store"
version = "0.5.3"
edition = "2021"

[dependencies]
nativelink-error = { path = "../nativelink-error" }
nativelink-config = { path = "../nativelink-config" }
nativelink-util = { path = "../nativelink-util" }
nativelink-proto = { path = "../nativelink-proto" }
nativelink-metric = { path = "../nativelink-metric" }
async-lock = { version = "3.4.0", features = ["std"], default-features = false }
async-trait = "0.1.83"
aws-config = { version = "1.5.10", default-features = false, features = [
  "rustls",
] }
aws-sdk-s3 = { version = "1.65.0", features = [
  "rt-tokio",
], default-features = false }
aws-smithy-runtime = { version = "1.7.4" }
bincode = "1.3.3"
blake3 = { version = "1.5.5", default-features = false }
byteorder = { version = "1.5.0", default-features = false }
bytes = { version = "1.9.0", default-features = false }
bytes-utils = { version = "0.1.4", default-features = false }
const_format = { version = "0.2.34", default-features = false }
filetime = "0.2.25"
fred = { version = "10.0.1", default-features = false, features = [
  "i-std",
  "i-scripts",
  "i-redisearch",
  "sha-1",
  "enable-rustls-ring",
  "metrics",
  "blocking-encoding",
  "custom-reconnect-errors",
  "sentinel-client",
  "sentinel-auth",
  "subscriber-client",
] }
patricia_tree = { version = "0.8.0", default-features = false }
futures = { version = "0.3.31", default-features = false }
hex = { version = "0.4.3", default-features = false }
http-body = "1.0.1"
hyper = { version = "0.14.31" }
hyper-rustls = { version = "0.24.2", default-features = false, features = [
  "webpki-roots",
] }
lz4_flex = { version = "0.11.3", default-features = false }
parking_lot = "0.12.3"
prost = { version = "0.13.4", default-features = false }
rand = { version = "0.8.5", default-features = false }
serde = { version = "1.0.216", default-features = false }
tokio = { version = "1.42.0", features = ["fs", "rt-multi-thread", "signal", "io-util"], default-features = false }
tokio-stream = { version = "0.1.17", features = ["fs"], default-features = false }
tokio-util = { version = "0.7.13" }
tonic = { version = "0.12.3", features = ["transport", "tls"], default-features = false }
tracing = { version = "0.1.41", default-features = false }
uuid = { version = "1.11.0", default-features = false, features = ["v4", "serde"] }
azure_storage_blobs = "0.21.0"
azure_core = {version= "0.21.0", default-features = false, features = ["stream"]}
azure_storage = "0.21.0"

[dev-dependencies]
nativelink-macro = { path = "../nativelink-macro" }
nativelink-metric-collector = { path = "../nativelink-metric-collector" }
pretty_assertions = { version = "1.4.1", features = ["std"] }
memory-stats = "1.2.0"
mock_instant = "0.5.1"
sha2 = { version = "0.10.8", default-features = false }
http = { version = "1.2.0", default-features = false }
aws-smithy-types = "1.2.9"
aws-smithy-runtime = { version = "1.7.4", features = [
  "test-util",
], default-features = false }
aws-sdk-s3 = { version = "1.65.0", features = [
  "rt-tokio",
], default-features = false }
aws-smithy-runtime-api = "1.7.3"
serial_test = { version = "3.2.0", features = [
  "async",
], default-features = false }
serde_json = "1.0.133"
fred = { version = "10.0.1", default-features = false, features = ["mocks"] }
tracing-subscriber = { version = "0.3.19", default-features = false }
