---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nativelink.yaml
  - worker.yaml
  - ../configmaps

images:
  - name: nativelink
  - name: nativelink-worker-init
  - name: nativelink-worker
