---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: nativelink-config
    files:
      - nativelink-config.json
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: worker
    files:
      - worker.json
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
