gcs_store:
  bucket: "example-bucket-name"
  key_prefix: "path/to/store/prefix/"
  credentials:
    gcs_auth_token: "YOUR_AUTH_TOKEN_HERE"
  retry:
    max_retries: 5
    initial_delay: 1  # In seconds
    max_delay: 30     # In seconds
    jitter: 0.2       # Jitter factor (0.2 means +/- 20%)
  upload:
    max_retry_buffer_per_request: 8388608  # 8MB
    resumable_chunk_size: 8388608          # 8MB
    resumable_max_concurrent_uploads: 3
  object_expiry_seconds: 86400  # 1 day
